//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppView.MediaWSReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaDTO", Namespace="http://schemas.datacontract.org/2004/07/AppService")]
    [System.SerializableAttribute()]
    public partial class MediaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BudgetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MediaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublishYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Budget {
            get {
                return this.BudgetField;
            }
            set {
                if ((this.BudgetField.Equals(value) != true)) {
                    this.BudgetField = value;
                    this.RaisePropertyChanged("Budget");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Director {
            get {
                return this.DirectorField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorField, value) != true)) {
                    this.DirectorField = value;
                    this.RaisePropertyChanged("Director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MediaID {
            get {
                return this.MediaIDField;
            }
            set {
                if ((this.MediaIDField.Equals(value) != true)) {
                    this.MediaIDField = value;
                    this.RaisePropertyChanged("MediaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublishYear {
            get {
                return this.PublishYearField;
            }
            set {
                if ((this.PublishYearField.Equals(value) != true)) {
                    this.PublishYearField = value;
                    this.RaisePropertyChanged("PublishYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MediaWSReference.IMedia")]
    public interface IMedia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/GetAllMedia", ReplyAction="http://tempuri.org/IMedia/GetAllMediaResponse")]
        AppView.MediaWSReference.MediaDTO[] GetAllMedia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/GetAllMedia", ReplyAction="http://tempuri.org/IMedia/GetAllMediaResponse")]
        System.Threading.Tasks.Task<AppView.MediaWSReference.MediaDTO[]> GetAllMediaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/IsMediaInserted", ReplyAction="http://tempuri.org/IMedia/IsMediaInsertedResponse")]
        bool IsMediaInserted(AppView.MediaWSReference.MediaDTO media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/IsMediaInserted", ReplyAction="http://tempuri.org/IMedia/IsMediaInsertedResponse")]
        System.Threading.Tasks.Task<bool> IsMediaInsertedAsync(AppView.MediaWSReference.MediaDTO media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/IsMediaUpdated", ReplyAction="http://tempuri.org/IMedia/IsMediaUpdatedResponse")]
        bool IsMediaUpdated(AppView.MediaWSReference.MediaDTO media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/IsMediaUpdated", ReplyAction="http://tempuri.org/IMedia/IsMediaUpdatedResponse")]
        System.Threading.Tasks.Task<bool> IsMediaUpdatedAsync(AppView.MediaWSReference.MediaDTO media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/IsMediaDeleted", ReplyAction="http://tempuri.org/IMedia/IsMediaDeletedResponse")]
        bool IsMediaDeleted(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/IsMediaDeleted", ReplyAction="http://tempuri.org/IMedia/IsMediaDeletedResponse")]
        System.Threading.Tasks.Task<bool> IsMediaDeletedAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMediaChannel : AppView.MediaWSReference.IMedia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediaClient : System.ServiceModel.ClientBase<AppView.MediaWSReference.IMedia>, AppView.MediaWSReference.IMedia {
        
        public MediaClient() {
        }
        
        public MediaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppView.MediaWSReference.MediaDTO[] GetAllMedia() {
            return base.Channel.GetAllMedia();
        }
        
        public System.Threading.Tasks.Task<AppView.MediaWSReference.MediaDTO[]> GetAllMediaAsync() {
            return base.Channel.GetAllMediaAsync();
        }
        
        public bool IsMediaInserted(AppView.MediaWSReference.MediaDTO media) {
            return base.Channel.IsMediaInserted(media);
        }
        
        public System.Threading.Tasks.Task<bool> IsMediaInsertedAsync(AppView.MediaWSReference.MediaDTO media) {
            return base.Channel.IsMediaInsertedAsync(media);
        }
        
        public bool IsMediaUpdated(AppView.MediaWSReference.MediaDTO media) {
            return base.Channel.IsMediaUpdated(media);
        }
        
        public System.Threading.Tasks.Task<bool> IsMediaUpdatedAsync(AppView.MediaWSReference.MediaDTO media) {
            return base.Channel.IsMediaUpdatedAsync(media);
        }
        
        public bool IsMediaDeleted(int ID) {
            return base.Channel.IsMediaDeleted(ID);
        }
        
        public System.Threading.Tasks.Task<bool> IsMediaDeletedAsync(int ID) {
            return base.Channel.IsMediaDeletedAsync(ID);
        }
    }
}
